on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   ggplot2: 'cran', r: 'release'}

          - {os: windows-latest, ggplot2: 'cran', r: 'release'}

          - {os: ubuntu-20.04,   ggplot2: 'cran', r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-20.04,   ggplot2: 'cran', r: 'release'}
          - {os: ubuntu-20.04,   ggplot2: 'cran', r: 'oldrel-1'}

          - {os: ubuntu-20.04,   ggplot2: 'dev',  r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install dev version of ggplot2
        if: matrix.config.ggplot2 == 'dev'
        with:
          extra-packages: any::tidyverse/ggplot2
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
